# Permalinks
permalink:           pretty

# Setup
title:               '[G]linmac'
tagline:             'SA & (Software|Data|Big Data|Platform) Engineer. Data enthusiast.'
description:         'Random notes, references and links about Big Data, software engineering and other related topics.'
url:                 http://glinmac.github.io
baseurl:             ''
paginate_path:       '/journal/page:num/'
paginate:            5

# About/contact
author:
  name:              Guillaume Gardey
  url:               https://glinmac.github.io
  email:             glinmac@gmail.com

github:
  repo:              https://github.com/glinmac

linkedin:
   address:          https://uk.linkedin.com/in/ggardey

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]

exclude: [vendor]

